name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install uuid
      run: sudo apt-get install uuid-dev python3-venv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m ivpm update
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
    - name: Save build result
      uses: actions/upload-artifact@v2
      with:
          name: psslangserver-linux_x64
          path: |
              build/psslangserver

  ci-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install uuid
      run: brew install ossp-uuid
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m ivpm update
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
    - name: Save build result
      uses: actions/upload-artifact@v2
      with:
          name: psslangserver-macos_x64
          path: |
              build/psslangserver

  ci-win32_x64:
    name: "Windows x64"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m pip install --upgrade ninja
        python -m ivpm update
    - name: Build
      run: |
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release 
        ninja
      shell: cmd
    - name: Save build result
      uses: actions/upload-artifact@v2
      with:
          name: psslangserver-win32_x64
          path: |
              build/psslangserver.exe
  ci-win32_x86:
    name: "Windows x86"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m pip install --upgrade ninja
        python -m ivpm update
    - name: Build
      run: |
        call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release 
        ninja
      shell: cmd
    - name: Save build result
      uses: actions/upload-artifact@v2
      with:
          name: psslangserver-win32_x86
          path: |
              build/psslangserver.exe

